# Generated by Django 3.1 on 2024-02-13 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_reviewratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewRatings',
            new_name='ReviewRating',
        ),
    ]
